version: "3.3"

services:
  app:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
    container_name: pyroute
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - ${PORT}:80
