name: Actions

on:
  push:
    branches:
      - main
    tags:
      - '*'
    pull_request:
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Poetry
      uses: Gr1N/setup-poetry@v7

    - name: Cache Poetry
      id: cache-poetry
      uses: actions/cache@v3
      env:
        cache-name: cache-poetry
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: poetry install

  lint:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Poetry
      uses: Gr1N/setup-poetry@v7

    - name: Cache Poetry
      id: cache-poetry
      uses: actions/cache@v3
      env:
        cache-name: cache-poetry
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Lint
      run: |
        poetry run pre-commit install
        poetry run pre-commit run -a -v

  test:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Poetry
      uses: Gr1N/setup-poetry@v7

    - name: Cache Poetry
      id: cache-poetry
      uses: actions/cache@v3
      env:
        cache-name: cache-poetry
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Test
      run: poetry run pytest -sx --cov
